In [1]:
import simpledbf
import os
import pandas as pd

PyTables is not installed. No support for HDF output.
SQLalchemy is not installed. No support for SQL output.

In [6]:
#path = '../../Downloads/19902000_WI_Election_Data_with_2017_Wards/WI_Election_Data_with_2017_Wards.dbf'
path = 'wi_2016_FEST/wi_2016.dbf'

dbf = simpledbf.Dbf5(path)
df = dbf.to_dataframe()

df.columns

Index(['OBJECTID_1', 'OBJECTID', 'GEOID', 'MCD_FIPS', 'CNTY_FIPS', 'LSAD',
       'NAME', 'ASM', 'SEN', 'CON', 'COUSUBFP', 'CNTY_NAME', 'STR_WARDS',
       'PERSONS', 'PERSONS18', 'WHITE', 'BLACK', 'HISPANIC', 'ASIAN',
       'AMINDIAN', 'PISLAND', 'OTHER', 'OTHERMLT', 'WHITE18', 'BLACK18',
       'HISPANIC18', 'ASIAN18', 'AMINDIAN18', 'PISLAND18', 'OTHER18',
       'OTHERMLT18', 'G16PRERTru', 'G16PREDCli', 'G16PRECCas', 'G16PRElJoh',
       'G16PREGSte', 'G16PREOth', 'G16USSRJoh', 'G16USSDFei', 'G16USSLAnd',
       'G16USSOth'],
      dtype='object')

In [39]:
ll[100:]

Index([], dtype='object')

In [46]:
df.iloc[:,20:30]

,PISLAND,OTHER,OTHERMLT,WHITE18,BLACK18,HISPANIC18,ASIAN18,AMINDIAN18,PISLAND18,OTHER18
0,0,0,0,442,0,8,1,3,0,0
1,0,3,0,425,0,1,2,5,0,1
2,0,0,0,217,0,3,0,0,0,0
3,0,0,1,563,2,16,2,1,0,0
4,0,0,0,618,2,2,7,3,0,0
5,0,0,0,419,0,6,0,5,0,0
6,0,0,1,718,1,15,4,4,0,0
7,0,0,0,491,1,5,0,5,0,0
8,0,0,0,504,0,13,1,1,0,0
9,0,0,0,446,0,2,0,0,0,0
10,0,0,0,705,3,6,3,1,0,0
11,0,0,0,506,2,1,13,2,0,0
12,0,0,0,401,0,6,9,3,0,0
13,0,0,0,522,0,4,34,3,0,0
14,0,0,1,595,1,1,19,2,0,0
15,0,0,0,328,0,3,15,1,0,0
16,0,1,0,593,0,1,28,1,0,1
17,0,0,1,722,0,10,24,3,0,0
18,0,0,0,452,0,1,26,2,0,0
19,0,4,2,451,2,9,29,0,0,0
20,0,0,2,398,0,3,24,0,0,0
21,0,1,0,697,0,4,4,3,0,0
22,0,3,0,578,1,2,1,8,0,3
23,0,0,0,665,3,5,11,10,0,0
24,0,1,1,635,8,8,14,2,0,0
25,0,0,0,657,0,5,31,4,0,0
26,0,0,0,721,8,2,17,7,0,0
27,1,0,3,667,3,5,17,2,1,0
28,3,1,0,688,1,5,27,3,3,0
29,0,1,0,524,1,0,20,2,0,1
...,...,...,...,...,...,...,...,...,...,...
6865,0,9,6,1182,13,34,57,17,0,2
6866,0,0,0,428,4,14,5,12,0,0
6867,1,1,1,1213,13,36,16,15,1,0
6868,0,5,0,338,2,11,6,8,0,1
6869,0,0,0,497,6,10,1,8,0,0
6870,0,1,3,628,3,6,9,5,0,0
6871,0,0,1,501,6,8,20,7,0,0
6872,0,1,4,887,16,34,43,17,0,0
6873,0,0,0,175,0,0,2,1,0,0
6874,0,0,0,558,2,5,20,6,0,0
6875,0,0,0,163,2,5,4,2,0,0
6876,4,1,0,1121,2,8,32,5,3,1
6877,1,0,0,715,0,10,21,8,1,0
6878,1,0,0,708,4,15,35,4,1,0
6879,0,0,0,278,2,1,3,3,0,0
6880,0,2,1,670,5,18,28,12,0,0
6881,1,0,0,838,5,5,23,6,1,0
6882,1,0,0,405,1,6,0,3,1,0
6883,1,0,0,626,2,12,14,3,1,0
6884,0,0,5,463,3,20,16,7,0,0
6885,0,0,2,268,2,5,14,5,0,0
6886,0,0,0,449,2,15,21,1,0,0
6887,0,0,0,101,0,0,1,0,0,0
6888,0,0,0,5,0,0,0,0,0,0
6889,0,0,0,0,0,0,0,0,0,0
6890,0,0,0,0,0,0,0,0,0,0
6891,0,0,0,20,0,0,1,4,0,0
6892,0,0,0,0,0,0,0,0,0,0
6893,0,0,0,0,0,0,0,0,0,0
6894,0,0,0,619,0,3,2,2,0,0